name: Update snap release

on:
  release:
    - published

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: 'Build the Snap package'
        uses: snapcore/action-build@v1
        id: snap-build

      - name: Upload snap
        uses: actions/upload-artifact@v3
        with:
          name: snap
          path: ${{ steps.snap-build.outputs.snap }}

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.snap-build.outputs.snap }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

